#!/usr/bin/env bash

set -x

cd "$(dirname "$0")"

# Compiled dotfiles
curl -L https://github.com/kokobd/dotfiles/releases/latest/download/dotfiles.tar.gz --output dotfiles.tar.gz
rm -rf rust
mkdir rust
tar xf dotfiles.tar.gz -C rust
./rust/bootstrap --region $CODER_REGION --ssh-private-key "$USER_SECRET"

# GPG
if [ ! -z "$(which gpg)" ]; then
  gpg --import ~/.gpg/private.gpg
fi

case "$GITHUB_REPOSITORY" in
  "bellroy/haskell")
    ./repo-setup/bellroy/haskell.sh
    ;;
  *)
    echo "Not running any repo specific setup"
    ;;
esac
